---

base_locale: en
locales: [en]

data:
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"

ignore_unused:
  - "decidim.components.friendly_signup.name"

ignore_missing:
  - decidim.participatory_processes.scopes.global
